"""Add Opening model

Revision ID: 15dd6a7e3374
Revises: a1b2c3d4e5f6
Create Date: 2026-05-26 00:38:32.596976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dd6a7e3374'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_game_number'), ['game_number'], unique=True)

    with op.batch_alter_table('openings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('white_win_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('black_win_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('draw_rate', sa.Float(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('variation',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_openings_eco_code'))
        batch_op.create_index(batch_op.f('ix_openings_eco_code'), ['eco_code'], unique=True)

    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzles_puzzle_number'), ['puzzle_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzles_puzzle_number'))

    with op.batch_alter_table('openings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openings_eco_code'))
        batch_op.create_index(batch_op.f('ix_openings_eco_code'), ['eco_code'], unique=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('variation',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('draw_rate')
        batch_op.drop_column('black_win_rate')
        batch_op.drop_column('white_win_rate')
        batch_op.drop_column('popularity')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_game_number'))

    # ### end Alembic commands ###
