"""initial chess database models

Revision ID: 4c0f851ac9b1
Revises: 
Create Date: 2026-05-18 23:24:10.403161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0f851ac9b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eco_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variation', sa.String(length=200), nullable=True),
    sa.Column('moves', sa.Text(), nullable=True, comment='JSON: 走法序列'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment='A/B/C/D/E类'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_openings_eco_code'), ['eco_code'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True, comment='GM/IM/FM/WGM等'),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('elo_rating', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_elo_rating'), ['elo_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)

    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('white_player_id', sa.Integer(), nullable=False),
    sa.Column('black_player_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True, comment='1-0/0-1/1/2-1/2/*'),
    sa.Column('pgn_content', sa.Text(), nullable=True),
    sa.Column('eco_code', sa.String(length=10), nullable=True),
    sa.Column('opening_name', sa.String(length=200), nullable=True),
    sa.Column('total_moves', sa.Integer(), nullable=True),
    sa.Column('final_fen', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_black_player_id'), ['black_player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_eco_code'), ['eco_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_white_player_id'), ['white_player_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('analysis_data', sa.Text(), nullable=True, comment='JSON: 完整分析数据'),
    sa.Column('opening_eco', sa.String(length=10), nullable=True),
    sa.Column('key_moves', sa.Text(), nullable=True, comment='JSON: 关键手列表'),
    sa.Column('win_rate_curve', sa.Text(), nullable=True, comment='JSON: 胜率曲线数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_game_id'), ['game_id'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))
        batch_op.drop_index(batch_op.f('ix_collections_game_id'))

    op.drop_table('collections')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_game_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_white_player_id'))
        batch_op.drop_index(batch_op.f('ix_games_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_games_eco_code'))
        batch_op.drop_index(batch_op.f('ix_games_date'))
        batch_op.drop_index(batch_op.f('ix_games_black_player_id'))

    op.drop_table('games')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))

    op.drop_table('tournaments')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_elo_rating'))
        batch_op.drop_index(batch_op.f('ix_players_country'))

    op.drop_table('players')
    with op.batch_alter_table('openings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openings_eco_code'))
        batch_op.drop_index(batch_op.f('ix_openings_category'))

    op.drop_table('openings')
    # ### end Alembic commands ###
